export default {
    PRIMARY_COLOR: '#2aabb8',
    TITLE_COLOR: 'green',
    HEADER_COLOR: 'blue',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_LARGE: 20,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#ebe9e9',
    BORDER_COLOR_LIGHT: '#ABACAB',
    CONTAINER_PADDING: 20,
    TEXT_INPUT_PADDING: 10,
    BORDER_WIDTH: 1,
  };
  